"""
                ---- View Functions ----

This file houses the different URLs that application implements

The functions below are also called handlers. Handlers are also called:
View Functions

Each View Function can be mapped to one or more URLs
"""

from app import db
from app.forms import RegistrationForm, EditProfileForm, ResetPasswordForm # from forms.py
from flask import render_template, flash, redirect, url_for, request# render_template method converts a template into an HTML page. This invokes Jinja2 template engine. Its shipped with Flask
from app import app # this references the app folder and the app instance inside __init__.py
from app.forms import LoginForm, EmptyForm, PostForm, RegistrationForm, EditProfileForm, ResetPasswordRequestForm
from datetime import datetime, timezone

import sqlalchemy as sa

from flask_login import current_user, login_user, logout_user, login_required # pip install flask_login
from app.models import User, Post
from app.email import send_password_reset_email

from urllib.parse import urlparse

# Above each function are URL routes
    # these are decorators, a decorator modifies the functions that follows it
    # a common pattern w/ decorators is to use them to register funcs as callbacks for certain events
@app.route('/', methods=['GET', 'POST'])        
@app.route('/index', methods=['GET', 'POST'])   
@login_required # this decorator will protect the view if the user is not logged in
def index():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(body=form.post.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post is now live')

        return redirect(url_for('index')) # standard practice to ALWAYS respond to a POST request generated by a web form submission with a redirect. 
                                          # Helps with how web browsers implement refresh command because a refresh button in a web browser will issue the last request, 
                                          # which in this case is a POST and we dont want to double that. So the redirect will send a GET request which is a more predictable way
                                          # this method is known as the Post/Redirect/Get pattern. It avoids inserting duplicate posts when a user inadvertently refreshes a page in a browser
    
    posts = db.session.scalars(current_user.following_posts()).all()
    # posts = [
    #     {
    #     'author':{'username':'John'},
    #     'body': 'Beatiful day in Portland!'
    #     },
    #     {
    #     'author':{'username':'Susan'},
    #     'body': 'Gran Turismo is an underdog movie. Recommmend!'
    #     }   
    #     ]
    page = request.args.get('page', 1, type=int)
    posts = db.paginate(current_user.following_posts(), page=page,
                        per_page=app.config['POSTS_PER_PAGE'], error_out=False)
    
        
    next_url = url_for('index', page=posts.next_num) if posts.has_next else None
    prev_url = url_for('index', page=posts.prev_num) if posts.has_prev else None

    return render_template('index.html', title = 'Home Page', form=form, posts = posts.items, next_url=next_url, prev_url=prev_url)

@app.route('/login', methods=['GET', 'POST']) # methods are the type of requests. We explicity tell our app what type of requests are accepted. Defualt is GET only
def login():
    if current_user.is_authenticated: # current_user belongs to Flask Login and is_authenticated is used to check if user is logged in or not
        return redirect(url_for('index'))

    form = LoginForm() # Instantiate an object from forms.py
    """
    The if statement below  will evaluate to True if the user clicks the submit button to POST data. So this will evaluate to true if user "posts" data via submit button
    Then it will look at forms > LoginForms to validate the data class. If all valid then eval to True
    So if the user triggers the POST method and the data is valid, then it will use flash, which is a method to show user its good
    """
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data): # evaluate to True if user is invalid/none or if the password is incorrect for user
            flash('Invalid username or password')
            return redirect(url_for('login')) # if wrong password entered by user then app will redirect back to the login page so it redisplays where the errors are for better UX
        
        # if user enters correct pw
        login_user(user, remember=form.remember_me.data) # if it makes to this step. the user is being logged in with login_user() and this function will regisyerthe user for navigation experience.

        # this variable is for requiring users to login. if they try to access a page and user not logged in. it will send them to login page
            # once they log in they will be redirected back to the page they tried to access before
        next_page = request.args.get('next') # this value will be set to a relative path. The @login_required. See page 51.

        if not next_page or urlparse(next_page).netloc != '': 
            # not next_page means if the login URL does not have a next argument then redirect to index page
            # url_parse(next_page).netloc != '' is to make site secure. if url is a full path then redirect to index page. the next_page value should always be a relative path not absolute path
                # url_parse() is a werkzeug method to help check if a URL is relative or absolute. See page 51
            # if one of the condition is met then set the next_page variable to 'index'
            next_page = url_for('index')

        return redirect(next_page) # redirects user to another page
    return render_template('login.html', title = 'Sign In', form = form)

@app.route('/logout') # this will be in in app/templates/base.html , which is the navigation bar. When the user logs in...the login button will turn into a logout button
def logout():
    logout_user() # this function lives in Flask Login library
    return redirect(url_for('index'))

@app.route('/register', methods=['GET','POST'])
def register():

    # first make sure the user that invokes this function is not ALREADY logged in. If so, redirect
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    
    form = RegistrationForm() # instantiate form var
    if form.validate_on_submit(): 
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congrats, you are now registered!')
        return redirect(url_for('login'))  # once the user succeeds on registering, it will send them back to login page to proceed
    return render_template('register.html', title='Register', form=form)

@app.route('/user/<username>') # <dynamic_component> , if that is in the route, it is a dynamic component
@login_required #this page is only accessible to logged in users
def user(username):
    user = db.first_or_404(sa.select(User).where(User.username == username))
    page = request.args.get('page', 1 , type=int)
    query = user.posts.select().order_by(Post.timestamp.desc())
    posts = db.paginate(query, page=page, per_page=app.config['POSTS_PER_PAGE'], error_out=False)

    next_url = url_for('user', username=user.username, page=posts.next_num) if posts.has_next else None
    prev_url = url_for('user', username=user.username, page=posts.prev_num) if posts.has_prev else None
    form = EmptyForm()
    # posts = [
    #     {'author': user, 'body': 'Test post #1'},
    #     {'author': user, 'body': 'Test post #2'}
    # ]
    form = EmptyForm() # need to instantiate the submit button
    return render_template('user.html', user=user, posts=posts.items, form=form, next_url=next_url, prev_url=prev_url)

@app.route('/edit_profile', methods=['GET','POST'])
@login_required
def edit_profile():
    form = EditProfileForm(original_username=current_user.username) # original_username is created to remember the username to check if it is duplicate
    if form.validate_on_submit(): # this is where the user will enter new data and submit it to the db
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()

        flash('Your changed have been saved.')
        form = EditProfileForm(formdata=None) # clear the data in the form
        # return redirect(url_for('edit_profile'))
        return render_template('edit_profile.html', title='Edit Profile', form=form) # clears the form
    elif request.method == 'GET': # when the user clicks on edit profile link it will prepopulate the form fields
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', title='Edit Profile', form=form)

@app.before_request # this decorator will register this before_request() function to run before the view function referenced, which is the login view. i think...or this code runs before ANY view function invoked
def before_request():
    if current_user.is_authenticated: # current_user is a flask method that is invoked in the login view
        current_user.last_seen = datetime.now(timezone.utc)
        db.session.commit() # there is no db.session.add() because the Flask-Login current_user method already invokes the user loader callback function that runs db already. you can do it again if youd like but it will violate DRY

@app.route('/follow/<username>', methods=['POST'])
@login_required
def follow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.username == username))
        if user is None:
            flash(f'User {username} not found.')
            return redirect(url_for('index'))
        if user == current_user:
            flash('You cannot follow yourself!')
            return redirect(url_for('user', username=username))
        current_user.follow(user)
        db.session.commit()
        flash(f'You are following {username}')        
        return redirect(url_for('user', username=username))
    else:
        return redirect(url_for('index'))
    
@app.route('/unfollow/<username>', methods=['POST'])
@login_required
def unfollow(username):
    form = EmptyForm()
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.username == username))
        if user is None:
            flash(f'User {username} not found.')
            return redirect(url_for('index'))
        if user == current_user:
            flash('You cannot unfollow yourself!')
            return redirect(url_for('user', username=username))
        current_user.unfollow(user)
        db.session.commit()
        flash(f'You are unfollowing {username}')        
        return redirect(url_for('user', username=username))
    else:
        return redirect(url_for('index'))
    

@app.route('/explore')
@login_required
def explore():
    # this view will re-use an existing template except will omit the form piece. There will be conditional statement in the index.html to stop it from rendering the form

    page = request.args.get('page', 1, type=int)
    query = sa.select(Post).order_by(Post.timestamp.desc())
    posts = db.paginate(query, page=page,
                        per_page=app.config['POSTS_PER_PAGE'], error_out=False)
    
    next_url = url_for('explore', page=posts.next_num) if posts.has_next else None
    prev_url = url_for('explore', page=posts.prev_num) if posts.has_prev else None

    
    return render_template('index.html', title= 'Explore', posts=posts.items, next_url=next_url, prev_url=prev_url) # if you look, form parameter is not in render_template() because we dont want to show form in this view

@app.route('/reset_password_request', methods=['GET','POST'])
def reset_password_request():
    # check is user is not logged in. If so, skip this function altogether and redirect to the index page
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        # when the form is submitted with email. we use that email to see if a user exists with this email provided
        # then if it is valid then pass that object to a helper function called send_password_reset_email()
        user = db.session.scalar(
            sa.select(User).where(User.email == form.email.data)
        )
        if user:
            send_password_reset_email(user)
        flash('Check your email for reset instructions') # notice this is flash is outside the if and will flash regardless if the email is unknown. this is so client cant use this form to figure if a member or not
        return redirect(url_for('login'))
    return render_template('reset_password_request.html', title= 'Reset Password', form=form)

@app.route('/reset_password/<token>', methods=['GET','POST'])
def reset_password(token):
    # check is user is not logged in. If so, skip this function altogether and redirect to the index page
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    user = User.verify_reset_password_token(token) # this method will only return user object if token is validated
    if not user:
        return redirect(url_for('index'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Your password has been reset')
        return redirect(url_for('login'))
    return render_template('reset_password.html', form=form)
