"""changed table names

Revision ID: b307d682b21d
Revises: 0296d1641962
Create Date: 2024-07-05 01:41:09.652742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b307d682b21d'
down_revision = '0296d1641962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_User_username'), ['username'], unique=True)

    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Post_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_Post_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_index('ix_user_info_email')
        batch_op.drop_index('ix_user_info_username')

    op.drop_table('user_info')
    with op.batch_alter_table('post_info', schema=None) as batch_op:
        batch_op.drop_index('ix_post_info_timestamp')
        batch_op.drop_index('ix_post_info_user_id')

    op.drop_table('post_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_info', schema=None) as batch_op:
        batch_op.create_index('ix_post_info_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_post_info_timestamp', ['timestamp'], unique=False)

    op.create_table('user_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.create_index('ix_user_info_username', ['username'], unique=1)
        batch_op.create_index('ix_user_info_email', ['email'], unique=1)

    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Post_user_id'))
        batch_op.drop_index(batch_op.f('ix_Post_timestamp'))

    op.drop_table('Post')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_username'))
        batch_op.drop_index(batch_op.f('ix_User_email'))

    op.drop_table('User')
    # ### end Alembic commands ###
